import { strict as assert } from "node:assert";
import { test } from "node:test";
import * as errors from "../src/errors.js";
import { ParseError, RegistrationError } from "../src/errors.js";

// Every expected string below was generated by running the corresponding Go
// template from go/strictcli/errors.go through fmt.Sprintf/fmt.Errorf with
// the same arguments -- the assertions pin byte-identical output.

// --- Catalog census ---

// Reconciliation against the conformance parity extractor
// (conformance/check_error_parity.py run against go/strictcli/errors.go):
// extract_go_errors yields 222 raw templates (200 func bodies + 22 consts),
// deduplicating to 219 unique normalized signatures. errors.ts exports one
// template function per raw Go template, hence 222, plus 4 templates with no
// errors.go body: errTagContractViolation (inline fmt.Sprintf in strictcli.go
// / Python _validate_tag_contracts), errHandlerReturnInvalid (Python
// _interpret_handler_return; inexpressible in Go), errOutcomeExitCodeNotInteger
// (TS-only factory guard), and errCommandFlagRelativeToRootUndeclared (Python
// _build_and_validate_command; Go validates markers with no command context).
// The config subphase adds 9 more with no errors.go body: 5 TOML-1.0
// acceptance-gate templates and 2 splice-verification templates (TS-only; the
// siblings' TOML parsers are 1.0-native), plus errAppConfigFormatBad and
// errAppConfigConflictModeBad (inline f-strings in Python App.__post_init__ /
// inline panics in Go option constructors).
// The checks subphase adds 1 more with no errors.go body:
// errCheckOutcomeDirectConstruction (Python _CheckOutcome.__post_init__ mint
// guard; Go seals the outcome structurally with unexported fields).
// The invoke/tool/MCP subphase adds 2 more with no errors.go body:
// errCallPathIsGroup (Python call() group-path message; Go inlines "no
// command resolved from path" in invoke.go) and errRouterCommandMustBeString
// (inline InvokeError literal in Go makeRouterTool / Python router execute).
// The error-parity task (6.4) centralizes 26 formerly-inline Python-wording
// templates with no errors.go body (Go's counterparts are inline or use
// different wording): 12 dict-flag parse templates + 2 positional-arg
// wrappers (values.ts), 9 registration templates (factories.ts), and 3
// check-provider materialization guards (app.ts / checks/provider.ts).
// The effects regime (5.4) adds 30: the §12 templates of the effects contract
// (classification, guard v2 / forwarding, framework-internal verification,
// grant declaration, effect call-time enforcement, effect failure, parameter
// rejection, inapplicable options, truncation, the aborted-preview marker and the confirm protocol), plus
// five effect argument type-guards Python raises as inline TypeErrors and one
// TS-only guard (errEffectsUnavailable) for a Context built outside a dispatch.
// promptConfirmConsequential is deliberately NOT counted here: it is a prompt,
// not an err* template, and the census filters on the err prefix.
// errCallConsequentialUnconsented adds 1: the programmatic-path refusal, the
// non-terminal counterpart of the confirm protocol's non-TTY error.
// The dry-run declaration adds 4: three registration guards
// (errCommandReadOnlyDryRunUnsupported, errCommandDryRunReasonMissing,
// errCommandDryRunReasonWithoutDeclaration -- the last has no errors.go body,
// because Go's WithDryRunUnsupported always sets both fields together) and the
// parse-time refusal (errDryRunNotSupported).
// The consent-parameter reservation adds 2: errFlagNameConsentReserved and
// errArgNameConsentReserved, the registration-time ban on declaring a flag or
// a positional arg named `approve_consequential` (the name the programmatic
// and MCP channels use to state consent).
// The declared payload schema adds 2: errPayloadSchemaInvalid (registration)
// and errPayloadInvalid (emission), the two OUTER templates of §19.5's
// validator. Its detail strings live in payload_schema.ts rather than here --
// they are pinned across implementations by the shared vector file, not by the
// error-parity catalog.
// The mutex-election round (contract §21) adds 2: errMutexRedundantNegation
// (the redundant-negation parse error) and errMutexDeclineClause (the teaching
// clause both decline-shaped errors carry).
// The presence round (contract §23, §12.12) is a net +3: it adds 10 and
// deletes 7. Added -- errFlagPresenceUndeclared / errArgPresenceUndeclared
// (nothing declared), errFlagPresenceDeclaredTwice / errArgPresenceDeclaredTwice
// (two declared), errFlagDefaultNullNotOptional / errArgDefaultNullNotOptional
// (the null-valued default's redirect), errFlagMutexMemberRequired (a mutex
// member declaring requiredness), errArgVariadicDefault (a variadic arg
// declaring a default), and the TS-only pair errFlagDefaultValueMissing /
// errArgDefaultValueMissing for `presence: "default"` written without a value,
// a half-written declaration no sibling spelling can express. Deleted -- the
// three `explicit empty default is redundant for <kind> flags` templates (an
// explicit [] or {} is a declaration now), errRequiredArgCannotHaveDefault
// (subsumed by the two-declared error), and the three arg-side list-default
// templates the round made unreachable: errArgListDefaultMustBeList,
// errArgExplicitEmptyDefaultRedundantList and
// errArgDefaultElementTypeMismatch. A list-typed arg must be variadic and a
// variadic arg refuses a default, so no arg can carry a list default for them
// to describe; the flag-side counterparts are untouched.
// The scoped-selector implementations' sweep (§18.19 item 221) adds 2:
// errShortShapeMismatch and errShortOnAmbiguousElection, the two short-reuse
// guards promoted from Python-authored to cross-language pinned templates --
// §24.7 permits sibling scopes to reuse a short and said nothing more, which
// left two states with a rule and no message.
// The schema-v2 round (§12.14) adds 2: errFlagChoiceMagnitude and
// errArgChoiceMagnitude, one condition on two surfaces -- an int choice whose
// magnitude a JSON reader's double cannot carry back. The clause after the
// colon is the payload regime's own, reused byte-for-byte.
// §24.7's choice-name charset adds 1: errChoiceNameCharset. TypeScript spells
// a choice name as a property key, which imposes no charset of its own, so the
// rule needs a runtime check like every other name ban.
// §25.4 removes 1: errArgChoicesIncompatibleListType, the last surviving copy
// of a rule the round deleted. Unifying the two variadic-arg spellings onto one
// published shape left the ban with no input that could reach it, and Go
// deleted its twin outright.
// §25.5's array row removes 1 more: errFlagChoicesIncompatibleCompound, the
// flag-side twin of the same deletion. Its condition was compound-wide while
// the only reachable half is dict-only -- the list half is the declaration
// whose enum belongs inside `items` -- and the dict half already has
// errFlagDictCannotCombineChoices. No TypeScript path ever called it.
// The required-flag sentence adds 1: errFlagRequired, which renders all three
// spellings of "nothing supplied this required flag" -- the two bool forms name
// the tokens that satisfy the requirement -- and takes the scope suffix as an
// argument, so root scope, inside a scope and both front doors render one
// sentence from one place (§12.13). The three inline templates it replaces were
// never catalogued.
// §12.15's constraint system nets +12: sixteen registration guards plus the
// two violation sentences are added (`constraintPrefix` is not an `err`
// template and does not count), and six go with `CoRequired` -- its three
// registration guards, the two family-specific unknown-flag templates that
// collapse onto the constraint's own name, and `errFlagsMustBeUsedTogether`,
// whose sentence is now `errAllOrNoneTogether`'s.
// §12.16's update-command construct nets +17: fifteen registration guards --
// the mutating-default ban, the eight name-and-record refusals, the three
// property-role/presence refusals and the two clear-vocabulary ones -- plus the
// two parse-time violations. `renderDeclFlag` and `renderDeclArg` are
// renderers rather than templates and do not count.
// The member-short round nets +2: the two places a short can be declared where
// no member flag exists to carry it -- on a token-spelled choice, and beside a
// payload-carrying member whose payload already declares one (§24.4, §24.12).
// Retired choices net +14: the six registration guards twinned across the flag
// and arg surfaces, plus the two parse-time refusals.
// The effects-bypass input rule nets +1: the refusal of a project root that is
// not a git work tree.
const EXPECTED_TEMPLATE_COUNT = 403;

function templateFunctions(): [string, (...args: never[]) => unknown][] {
	// Widen to unknown first: the module also exports the two error classes,
	// whose constructor types break a direct function-shaped type predicate.
	const entries: [string, unknown][] = Object.entries(errors);
	return entries.filter(
		(entry): entry is [string, (...args: never[]) => unknown] =>
			entry[0].startsWith("err") && typeof entry[1] === "function",
	);
}

test("catalog exports exactly the extractor's template count", () => {
	assert.equal(templateFunctions().length, EXPECTED_TEMPLATE_COUNT);
});

test("template function names are unique and follow errXxx naming", () => {
	const names = templateFunctions().map(([name]) => name);
	assert.equal(new Set(names).size, names.length);
	for (const name of names) {
		assert.match(name, /^err[A-Z]/);
	}
});

test("every template returns a non-empty string for dummy args", () => {
	// Max template arity is 4. Number-typed slots interpolate string dummies
	// just as well for the non-emptiness check.
	for (const [name, fn] of templateFunctions()) {
		const out = (fn as (...args: unknown[]) => unknown)("a", "b", "c", "d");
		assert.equal(typeof out, "string", name);
		assert.ok((out as string).length > 0, name);
	}
});

// --- Byte-parity samples: parse-time section templates ---

test("parse-time templates are byte-identical to sibling output", () => {
	assert.equal(errors.errUnknownFlag("--unknown"), "unknown flag '--unknown'");
	assert.equal(
		errors.errFlagInvalidChoice("format", "xml", "text, json"),
		"--format: invalid value 'xml', must be one of: text, json",
	);
	assert.equal(
		errors.errArgInvalidChoice("mode", "fast", "slow, safe"),
		"argument 'mode': invalid value 'fast', must be one of: slow, safe",
	);
	assert.equal(errors.errUnknownCommand("deploy"), "unknown command 'deploy'");
	assert.equal(
		errors.errUnknownCommandInGroup("push", "myapp remote"),
		"unknown command 'push' in 'myapp remote'",
	);
	assert.equal(
		errors.errMissingRequiredArgument("target"),
		"missing required argument 'target'",
	);
	assert.equal(
		errors.errUnexpectedArgument("extra"),
		"unexpected argument 'extra'",
	);
	assert.equal(
		errors.errCommandDeprecated("old-cmd", "use 'new-cmd' instead"),
		"command 'old-cmd' is deprecated: use 'new-cmd' instead",
	);
	assert.equal(
		errors.errBoolFlagNoValue("--verbose"),
		"flag '--verbose' is a boolean flag and does not take a value",
	);
	assert.equal(
		errors.errBoolNegationNoValue("--no-verbose"),
		"flag '--no-verbose' is a boolean negation and does not take a value",
	);
	assert.equal(
		errors.errFlagRequiresValue("--target"),
		"flag '--target' requires a value",
	);
	assert.equal(
		errors.errFlagDuplicateValue("tag", "web"),
		"--tag: duplicate value 'web'",
	);
	assert.equal(
		errors.errInvalidBoolEnvValue("maybe", "MYAPP_VERBOSE", "verbose"),
		"invalid boolean value 'maybe' for env var 'MYAPP_VERBOSE' (flag '--verbose')",
	);
	assert.equal(
		errors.errMutuallyExclusive("--json, --quiet"),
		"--json, --quiet are mutually exclusive",
	);
	assert.equal(
		errors.errOneOfRequired("--json, --quiet", ""),
		"one of --json, --quiet is required",
	);
	assert.equal(
		errors.errOneOfRequired(
			"--json, --quiet",
			errors.errMutexDeclineClause("quiet"),
		),
		"one of --json, --quiet is required " +
			"(--no-quiet declines an option; it does not choose one)",
	);
	assert.equal(
		errors.errMutexRedundantNegation(
			"--no-quiet",
			"json",
			errors.errMutexDeclineClause("quiet"),
		),
		"--no-quiet cannot be combined with --json " +
			"(--no-quiet declines an option; it does not choose one)",
	);
	// Every constraint sentence carries the `constraint "<c>": ` prefix, in
	// DOUBLE quotes: a declared identifier is double-quoted and a token the
	// operator typed is single-quoted (§12.15).
	assert.equal(
		errors.errFlagRequiresFlag("serve-dep", "watch", "serve"),
		"constraint \"serve-dep\": flag '--watch' requires '--serve'",
	);
	assert.equal(
		errors.errAllOrNoneTogether("creds", "--user, --pass"),
		'constraint "creds": --user, --pass must be used together',
	);
	assert.equal(
		errors.errAtLeastOneRequired(
			"purge-selection",
			"targets, --older-than, --all",
			"",
		),
		'constraint "purge-selection": at least one of targets, --older-than, --all is required',
	);
	assert.equal(
		errors.errAtLeastOneRequired(
			"purge-selection",
			"targets, --all",
			errors.errMutexDeclineClause("all"),
		),
		'constraint "purge-selection": at least one of targets, --all is required ' +
			"(--no-all declines an option; it does not choose one)",
	);
	assert.equal(
		errors.errImpliesConflict("sync", "push", "", "commit", "no-"),
		"constraint \"sync\": flag '--push' implies '--commit', but '--no-commit' was explicitly provided",
	);
	assert.equal(
		errors.errHermeticConfigMutuallyExclusive(),
		"--hermetic and --config are mutually exclusive",
	);
	assert.equal(
		errors.errWrappedFromEnvVar("expected integer, got 'x'", "MYAPP_COUNT"),
		"expected integer, got 'x' (from env var 'MYAPP_COUNT')",
	);
	assert.equal(
		errors.errFlagErrFromEnvVar(
			"count",
			"expected integer, got 'x'",
			"MYAPP_COUNT",
		),
		"--count: expected integer, got 'x' (from env var 'MYAPP_COUNT')",
	);
	assert.equal(
		errors.errAtPrefixFileNotFound("body", "/tmp/missing.txt"),
		"--body: file not found: /tmp/missing.txt",
	);
	assert.equal(errors.errNoCommandSpecified(), "no command specified");
	assert.equal(
		errors.errFlagSetInBothCliAndConfig("verbose"),
		"flag 'verbose' set in both cli and config; remove one",
	);
});

// --- Byte-parity samples: strict scalar parsing templates ---
// (Section "parse.go — strict parsing" carries no "(parse-time)" marker
// because these are wrapped with a flag/arg prefix at their call sites.)

test("strict scalar parsing templates are byte-identical to sibling output", () => {
	assert.equal(errors.errExpectedInteger("abc"), "expected integer, got 'abc'");
	assert.equal(
		errors.errExpectedBoolean("maybe"),
		"expected boolean, got 'maybe'",
	);
	assert.equal(errors.errExpectedFloat("1.2.3"), "expected float, got '1.2.3'");
	assert.equal(errors.errNaNNotAllowed(), "NaN is not allowed");
	assert.equal(errors.errInfNotAllowed(), "Inf is not allowed");
});

// --- Byte-parity samples: registration-time section templates ---

test("registration templates are byte-identical to sibling output", () => {
	assert.equal(
		errors.errInvalidTagName("My Tag"),
		'invalid tag name "My Tag": must match [a-z][a-z0-9-]*',
	);
	assert.equal(
		errors.errFlagForceReserved(),
		"flag 'force' is a reserved name; use a qualified name like 'force-overwrite' or 'force-delete'",
	);
	assert.equal(
		errors.errFlagNoPrefixReserved("no-commit"),
		"flag 'no-commit': names starting with 'no-' are reserved for the negation system; use a positive name instead",
	);
	assert.equal(
		errors.errSelectorNoChoices("via"),
		'Flag "via": a choice flag must declare at least two choices',
	);
	assert.equal(
		errors.errFlagRepeatableIncompatibleBool("verbose"),
		'Flag "verbose": repeatable is incompatible with type=bool',
	);
	assert.equal(
		errors.errArgListTypeRequiresVariadic("files"),
		'Arg "files": list type requires variadic=true',
	);
	assert.equal(
		errors.errArgDefaultNotInChoices("mode", "fast", "slow, safe"),
		"Arg \"mode\": default 'fast' is not in choices [slow, safe]",
	);
	assert.equal(
		errors.errGroupCollidesWithCommand("remote"),
		'group "remote" collides with an existing command',
	);
	assert.equal(
		errors.errChecksTomlMissingApp(),
		'checks.toml: missing required top-level key "app"',
	);
	assert.equal(
		errors.errChecksTomlSeverityInvalid("lint", "critical"),
		'checks.toml: check "lint": "severity" must be "error" or "warn", got "critical"',
	);
	assert.equal(
		errors.errCommandEnvVarPrefix("build", "TARGET", "target", "MYAPP_"),
		'command "build": env var "TARGET" for flag "target" must start with "MYAPP_" (or set prefixed=false)',
	);
	assert.equal(errors.errAppHelpEmpty(), "App.help must be a non-empty string");
	assert.equal(
		errors.errWithConfigConflictModeBadMode("both"),
		'WithConfigConflictMode: mode must be "cli-wins" or "error", got "both"',
	);
	assert.equal(
		errors.errDuplicateGlobalFlag("verbose"),
		'duplicate global flag name "verbose"',
	);
	assert.equal(
		errors.errCheckSeverityMismatch(
			"lint",
			"warn",
			"RegisterCheck",
			"RegisterWarnCheck",
		),
		'check "lint": declared severity "warn" in checks.toml but registered via RegisterCheck; use RegisterWarnCheck',
	);
	assert.equal(
		errors.errFlagDefaultElementError("ports", 2, "expected integer, got 'x'"),
		"Flag \"ports\": default element 2: expected integer, got 'x'",
	);
	assert.equal(
		errors.errTagExprUnexpectedChar("@", 5),
		'tag expression: unexpected character "@" at position 5',
	);
	assert.equal(
		errors.errConfigFieldNameInvalid("Bad.Name"),
		'ConfigField name "Bad.Name" is invalid: must match [a-z][a-z0-9_]*(.[a-z][a-z0-9_]*)* (lowercase, dots for sections)',
	);
	assert.equal(
		errors.errSchemaMismatch("old-proj", "new-proj"),
		"Schema mismatch: existing schema belongs to project 'old-proj', not 'new-proj'. Run from the correct project directory.",
	);
});

// --- Go %q (strconv.Quote) edge cases, verified against Go output ---

test("%q slots quote exactly like Go strconv.Quote", () => {
	assert.equal(
		errors.errInvalidTagName('a"b'),
		'invalid tag name "a\\"b": must match [a-z][a-z0-9-]*',
	);
	assert.equal(
		errors.errInvalidTagName("a\\b"),
		'invalid tag name "a\\\\b": must match [a-z][a-z0-9-]*',
	);
	assert.equal(
		errors.errInvalidTagName("a\tb"),
		'invalid tag name "a\\tb": must match [a-z][a-z0-9-]*',
	);
	assert.equal(
		errors.errInvalidTagName("a\nb"),
		'invalid tag name "a\\nb": must match [a-z][a-z0-9-]*',
	);
	assert.equal(
		errors.errInvalidTagName("a\x01b"),
		'invalid tag name "a\\x01b": must match [a-z][a-z0-9-]*',
	);
	assert.equal(
		errors.errInvalidTagName("café"),
		'invalid tag name "café": must match [a-z][a-z0-9-]*',
	);
});

// --- Error classes ---

test("RegistrationError carries only a message", () => {
	const e = new RegistrationError("boom");
	assert.ok(e instanceof Error);
	assert.ok(e instanceof RegistrationError);
	assert.equal(e.name, "RegistrationError");
	assert.equal(e.message, "boom");
});

test("ParseError carries only a message", () => {
	const e = new ParseError("bad flag");
	assert.ok(e instanceof Error);
	assert.ok(e instanceof ParseError);
	assert.equal(e.name, "ParseError");
	assert.equal(e.message, "bad flag");
});

test("the two error classes are distinct", () => {
	assert.ok(!(new ParseError("x") instanceof RegistrationError));
	assert.ok(!(new RegistrationError("x") instanceof ParseError));
});
