[[releasables]]
name = "py-strictcli"

[[releasables]]
name = "go-strictcli"

[[releasables]]
name = "ts-strictcli"

[[projects]]
path = "python"
name = "strictcli"
releasable = "py-strictcli"

[[projects]]
path = "go"
name = "go-strictcli"
releasable = "go-strictcli"

[[projects]]
path = "typescript"
name = "ts-strictcli"
releasable = "ts-strictcli"

[[projects]]
path = "conformance"
name = "conformance"
dev_only = true
releasable = false

[[projects]]
path = "."
name = "root"
dev_only = true
releasable = false
