"""Replay the committed SCF float vectors against the Python formatter.

The vectors live at ``go/strictcli/testdata/float_vectors.json`` and are generated by
``conformance/gen_float_vectors.py`` from this very formatter (the reference
implementation). Asserting the formatter still reproduces every recorded SCF
string pins the reference against accidental drift; the Go suite replays the
same file to prove cross-language byte agreement.
"""

from __future__ import annotations

import json
import struct
from pathlib import Path

import pytest

import strictcli

VECTORS_PATH = (
    Path(__file__).resolve().parents[2] / "go" / "strictcli" / "testdata" / "float_vectors.json"
)


def _load_vectors() -> list[tuple[int, str]]:
    doc = json.loads(VECTORS_PATH.read_text())
    return [(int(v["bits"], 16), v["scf"]) for v in doc["vectors"]]


def _from_bits(bits: int) -> float:
    return struct.unpack("<d", struct.pack("<Q", bits))[0]


VECTORS = _load_vectors()


def test_vectors_present():
    # Sanity: the battery + adversarial set is substantial.
    assert len(VECTORS) > 500


@pytest.mark.parametrize("bits,expected", VECTORS)
def test_python_formatter_matches_vector(bits: int, expected: str):
    x = _from_bits(bits)
    got = strictcli._format_float_canonical(x)
    assert got == expected, (
        f"bits={bits:016x} python SCF={got!r} != recorded {expected!r}"
    )


@pytest.mark.parametrize("bits,expected", VECTORS)
def test_vector_round_trips(bits: int, expected: str):
    # The recorded SCF string must parse back to the identical double.
    x = _from_bits(bits)
    back = float(expected)
    assert struct.pack("<Q", bits) == struct.pack("<d", back), (
        f"bits={bits:016x} SCF={expected!r} round-tripped to a different double"
    )
